server:
  port: 8001
spring:
  application:
    name: common-service
  cloud:
    consul:
      enabled: false
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  config:
    enabled: true
    import: "optional:consul:"
management:
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: ALWAYS
#      show-components: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"