#write docker-compose.yml for this microservices project
version: '3.7'
services:
  consul:
    image: consul:1.15
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    command: agent -server -ui -bootstrap-expect=1
    ports:
        - "8500:8500"
        - "8600:8600"
        - "8600:8600/udp"
  gatway:
    build:
      context: ./gateway
      target: development
    ports:
      - "8000:8000"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
  common-service:
    build:
      context: ./common-service
      target: development
    ports:
      - "8001:8081"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
  user-service:
    build:
      context: ./user-service
      target: development
    ports:
        - "8002:8082"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul

