#set up gateway for the user service and common service, user service is hosted on localhost with port 8081, and common service is hosted on  port 8082
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: common-service
          uri: lb://common-service
          predicates:
            - Path=/common/**
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


