apiVersion: 1
datasources:
  - name: Tempo
    apiVersion: 1
    version: 1
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    isDefault: true
    editable: false
