apiVersion: 1
datasources:
  - name: Tempo
    apiVersion: 1
    version: 1
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    isDefault: true
    editable: false
  - name: Prometheus
    apiVersion: 1
    version: 1
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    isDefault: false
    editable: false
