receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
processors:
  batch:
exporters:
  debug:
    verbosity: detailed
  otlphttp/tempo:
    endpoint: http://tempo:3202
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:8889'
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
